
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AuthenticationAudit` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model AuthenticationAudit
 * 
 */
export type AuthenticationAuditModel = runtime.Types.Result.DefaultSelection<Prisma.$AuthenticationAuditPayload>

export type AggregateAuthenticationAudit = {
  _count: AuthenticationAuditCountAggregateOutputType | null
  _avg: AuthenticationAuditAvgAggregateOutputType | null
  _sum: AuthenticationAuditSumAggregateOutputType | null
  _min: AuthenticationAuditMinAggregateOutputType | null
  _max: AuthenticationAuditMaxAggregateOutputType | null
}

export type AuthenticationAuditAvgAggregateOutputType = {
  userId: number | null
}

export type AuthenticationAuditSumAggregateOutputType = {
  userId: number | null
}

export type AuthenticationAuditMinAggregateOutputType = {
  id: string | null
  ipAddress: string | null
  remotePort: string | null
  userAgent: string | null
  origin: string | null
  status: $Enums.AuthenticationStatus | null
  userId: number | null
  createdAt: Date | null
}

export type AuthenticationAuditMaxAggregateOutputType = {
  id: string | null
  ipAddress: string | null
  remotePort: string | null
  userAgent: string | null
  origin: string | null
  status: $Enums.AuthenticationStatus | null
  userId: number | null
  createdAt: Date | null
}

export type AuthenticationAuditCountAggregateOutputType = {
  id: number
  ipAddress: number
  remotePort: number
  userAgent: number
  origin: number
  status: number
  userId: number
  createdAt: number
  _all: number
}


export type AuthenticationAuditAvgAggregateInputType = {
  userId?: true
}

export type AuthenticationAuditSumAggregateInputType = {
  userId?: true
}

export type AuthenticationAuditMinAggregateInputType = {
  id?: true
  ipAddress?: true
  remotePort?: true
  userAgent?: true
  origin?: true
  status?: true
  userId?: true
  createdAt?: true
}

export type AuthenticationAuditMaxAggregateInputType = {
  id?: true
  ipAddress?: true
  remotePort?: true
  userAgent?: true
  origin?: true
  status?: true
  userId?: true
  createdAt?: true
}

export type AuthenticationAuditCountAggregateInputType = {
  id?: true
  ipAddress?: true
  remotePort?: true
  userAgent?: true
  origin?: true
  status?: true
  userId?: true
  createdAt?: true
  _all?: true
}

export type AuthenticationAuditAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AuthenticationAudit to aggregate.
   */
  where?: Prisma.AuthenticationAuditWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AuthenticationAudits to fetch.
   */
  orderBy?: Prisma.AuthenticationAuditOrderByWithRelationInput | Prisma.AuthenticationAuditOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AuthenticationAuditWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AuthenticationAudits from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AuthenticationAudits.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AuthenticationAudits
  **/
  _count?: true | AuthenticationAuditCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: AuthenticationAuditAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: AuthenticationAuditSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AuthenticationAuditMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AuthenticationAuditMaxAggregateInputType
}

export type GetAuthenticationAuditAggregateType<T extends AuthenticationAuditAggregateArgs> = {
      [P in keyof T & keyof AggregateAuthenticationAudit]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAuthenticationAudit[P]>
    : Prisma.GetScalarType<T[P], AggregateAuthenticationAudit[P]>
}




export type AuthenticationAuditGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AuthenticationAuditWhereInput
  orderBy?: Prisma.AuthenticationAuditOrderByWithAggregationInput | Prisma.AuthenticationAuditOrderByWithAggregationInput[]
  by: Prisma.AuthenticationAuditScalarFieldEnum[] | Prisma.AuthenticationAuditScalarFieldEnum
  having?: Prisma.AuthenticationAuditScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AuthenticationAuditCountAggregateInputType | true
  _avg?: AuthenticationAuditAvgAggregateInputType
  _sum?: AuthenticationAuditSumAggregateInputType
  _min?: AuthenticationAuditMinAggregateInputType
  _max?: AuthenticationAuditMaxAggregateInputType
}

export type AuthenticationAuditGroupByOutputType = {
  id: string
  ipAddress: string | null
  remotePort: string | null
  userAgent: string | null
  origin: string | null
  status: $Enums.AuthenticationStatus
  userId: number | null
  createdAt: Date
  _count: AuthenticationAuditCountAggregateOutputType | null
  _avg: AuthenticationAuditAvgAggregateOutputType | null
  _sum: AuthenticationAuditSumAggregateOutputType | null
  _min: AuthenticationAuditMinAggregateOutputType | null
  _max: AuthenticationAuditMaxAggregateOutputType | null
}

export type GetAuthenticationAuditGroupByPayload<T extends AuthenticationAuditGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AuthenticationAuditGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AuthenticationAuditGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AuthenticationAuditGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AuthenticationAuditGroupByOutputType[P]>
      }
    >
  >



export type AuthenticationAuditWhereInput = {
  AND?: Prisma.AuthenticationAuditWhereInput | Prisma.AuthenticationAuditWhereInput[]
  OR?: Prisma.AuthenticationAuditWhereInput[]
  NOT?: Prisma.AuthenticationAuditWhereInput | Prisma.AuthenticationAuditWhereInput[]
  id?: Prisma.StringFilter<"AuthenticationAudit"> | string
  ipAddress?: Prisma.StringNullableFilter<"AuthenticationAudit"> | string | null
  remotePort?: Prisma.StringNullableFilter<"AuthenticationAudit"> | string | null
  userAgent?: Prisma.StringNullableFilter<"AuthenticationAudit"> | string | null
  origin?: Prisma.StringNullableFilter<"AuthenticationAudit"> | string | null
  status?: Prisma.EnumAuthenticationStatusFilter<"AuthenticationAudit"> | $Enums.AuthenticationStatus
  userId?: Prisma.IntNullableFilter<"AuthenticationAudit"> | number | null
  createdAt?: Prisma.DateTimeFilter<"AuthenticationAudit"> | Date | string
  user?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}

export type AuthenticationAuditOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  ipAddress?: Prisma.SortOrderInput | Prisma.SortOrder
  remotePort?: Prisma.SortOrderInput | Prisma.SortOrder
  userAgent?: Prisma.SortOrderInput | Prisma.SortOrder
  origin?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  userId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type AuthenticationAuditWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.AuthenticationAuditWhereInput | Prisma.AuthenticationAuditWhereInput[]
  OR?: Prisma.AuthenticationAuditWhereInput[]
  NOT?: Prisma.AuthenticationAuditWhereInput | Prisma.AuthenticationAuditWhereInput[]
  ipAddress?: Prisma.StringNullableFilter<"AuthenticationAudit"> | string | null
  remotePort?: Prisma.StringNullableFilter<"AuthenticationAudit"> | string | null
  userAgent?: Prisma.StringNullableFilter<"AuthenticationAudit"> | string | null
  origin?: Prisma.StringNullableFilter<"AuthenticationAudit"> | string | null
  status?: Prisma.EnumAuthenticationStatusFilter<"AuthenticationAudit"> | $Enums.AuthenticationStatus
  userId?: Prisma.IntNullableFilter<"AuthenticationAudit"> | number | null
  createdAt?: Prisma.DateTimeFilter<"AuthenticationAudit"> | Date | string
  user?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}, "id">

export type AuthenticationAuditOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  ipAddress?: Prisma.SortOrderInput | Prisma.SortOrder
  remotePort?: Prisma.SortOrderInput | Prisma.SortOrder
  userAgent?: Prisma.SortOrderInput | Prisma.SortOrder
  origin?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  userId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.AuthenticationAuditCountOrderByAggregateInput
  _avg?: Prisma.AuthenticationAuditAvgOrderByAggregateInput
  _max?: Prisma.AuthenticationAuditMaxOrderByAggregateInput
  _min?: Prisma.AuthenticationAuditMinOrderByAggregateInput
  _sum?: Prisma.AuthenticationAuditSumOrderByAggregateInput
}

export type AuthenticationAuditScalarWhereWithAggregatesInput = {
  AND?: Prisma.AuthenticationAuditScalarWhereWithAggregatesInput | Prisma.AuthenticationAuditScalarWhereWithAggregatesInput[]
  OR?: Prisma.AuthenticationAuditScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AuthenticationAuditScalarWhereWithAggregatesInput | Prisma.AuthenticationAuditScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"AuthenticationAudit"> | string
  ipAddress?: Prisma.StringNullableWithAggregatesFilter<"AuthenticationAudit"> | string | null
  remotePort?: Prisma.StringNullableWithAggregatesFilter<"AuthenticationAudit"> | string | null
  userAgent?: Prisma.StringNullableWithAggregatesFilter<"AuthenticationAudit"> | string | null
  origin?: Prisma.StringNullableWithAggregatesFilter<"AuthenticationAudit"> | string | null
  status?: Prisma.EnumAuthenticationStatusWithAggregatesFilter<"AuthenticationAudit"> | $Enums.AuthenticationStatus
  userId?: Prisma.IntNullableWithAggregatesFilter<"AuthenticationAudit"> | number | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"AuthenticationAudit"> | Date | string
}

export type AuthenticationAuditCreateInput = {
  id?: string
  ipAddress?: string | null
  remotePort?: string | null
  userAgent?: string | null
  origin?: string | null
  status: $Enums.AuthenticationStatus
  createdAt?: Date | string
  user?: Prisma.UserCreateNestedOneWithoutAuthenticationAuditsInput
}

export type AuthenticationAuditUncheckedCreateInput = {
  id?: string
  ipAddress?: string | null
  remotePort?: string | null
  userAgent?: string | null
  origin?: string | null
  status: $Enums.AuthenticationStatus
  userId?: number | null
  createdAt?: Date | string
}

export type AuthenticationAuditUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  ipAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  remotePort?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userAgent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  origin?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumAuthenticationStatusFieldUpdateOperationsInput | $Enums.AuthenticationStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneWithoutAuthenticationAuditsNestedInput
}

export type AuthenticationAuditUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  ipAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  remotePort?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userAgent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  origin?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumAuthenticationStatusFieldUpdateOperationsInput | $Enums.AuthenticationStatus
  userId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AuthenticationAuditCreateManyInput = {
  id?: string
  ipAddress?: string | null
  remotePort?: string | null
  userAgent?: string | null
  origin?: string | null
  status: $Enums.AuthenticationStatus
  userId?: number | null
  createdAt?: Date | string
}

export type AuthenticationAuditUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  ipAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  remotePort?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userAgent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  origin?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumAuthenticationStatusFieldUpdateOperationsInput | $Enums.AuthenticationStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AuthenticationAuditUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  ipAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  remotePort?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userAgent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  origin?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumAuthenticationStatusFieldUpdateOperationsInput | $Enums.AuthenticationStatus
  userId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AuthenticationAuditCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  ipAddress?: Prisma.SortOrder
  remotePort?: Prisma.SortOrder
  userAgent?: Prisma.SortOrder
  origin?: Prisma.SortOrder
  status?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AuthenticationAuditAvgOrderByAggregateInput = {
  userId?: Prisma.SortOrder
}

export type AuthenticationAuditMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  ipAddress?: Prisma.SortOrder
  remotePort?: Prisma.SortOrder
  userAgent?: Prisma.SortOrder
  origin?: Prisma.SortOrder
  status?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AuthenticationAuditMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  ipAddress?: Prisma.SortOrder
  remotePort?: Prisma.SortOrder
  userAgent?: Prisma.SortOrder
  origin?: Prisma.SortOrder
  status?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AuthenticationAuditSumOrderByAggregateInput = {
  userId?: Prisma.SortOrder
}

export type AuthenticationAuditListRelationFilter = {
  every?: Prisma.AuthenticationAuditWhereInput
  some?: Prisma.AuthenticationAuditWhereInput
  none?: Prisma.AuthenticationAuditWhereInput
}

export type AuthenticationAuditOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type EnumAuthenticationStatusFieldUpdateOperationsInput = {
  set?: $Enums.AuthenticationStatus
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type AuthenticationAuditCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.AuthenticationAuditCreateWithoutUserInput, Prisma.AuthenticationAuditUncheckedCreateWithoutUserInput> | Prisma.AuthenticationAuditCreateWithoutUserInput[] | Prisma.AuthenticationAuditUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.AuthenticationAuditCreateOrConnectWithoutUserInput | Prisma.AuthenticationAuditCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.AuthenticationAuditCreateManyUserInputEnvelope
  connect?: Prisma.AuthenticationAuditWhereUniqueInput | Prisma.AuthenticationAuditWhereUniqueInput[]
}

export type AuthenticationAuditUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.AuthenticationAuditCreateWithoutUserInput, Prisma.AuthenticationAuditUncheckedCreateWithoutUserInput> | Prisma.AuthenticationAuditCreateWithoutUserInput[] | Prisma.AuthenticationAuditUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.AuthenticationAuditCreateOrConnectWithoutUserInput | Prisma.AuthenticationAuditCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.AuthenticationAuditCreateManyUserInputEnvelope
  connect?: Prisma.AuthenticationAuditWhereUniqueInput | Prisma.AuthenticationAuditWhereUniqueInput[]
}

export type AuthenticationAuditUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.AuthenticationAuditCreateWithoutUserInput, Prisma.AuthenticationAuditUncheckedCreateWithoutUserInput> | Prisma.AuthenticationAuditCreateWithoutUserInput[] | Prisma.AuthenticationAuditUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.AuthenticationAuditCreateOrConnectWithoutUserInput | Prisma.AuthenticationAuditCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.AuthenticationAuditUpsertWithWhereUniqueWithoutUserInput | Prisma.AuthenticationAuditUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.AuthenticationAuditCreateManyUserInputEnvelope
  set?: Prisma.AuthenticationAuditWhereUniqueInput | Prisma.AuthenticationAuditWhereUniqueInput[]
  disconnect?: Prisma.AuthenticationAuditWhereUniqueInput | Prisma.AuthenticationAuditWhereUniqueInput[]
  delete?: Prisma.AuthenticationAuditWhereUniqueInput | Prisma.AuthenticationAuditWhereUniqueInput[]
  connect?: Prisma.AuthenticationAuditWhereUniqueInput | Prisma.AuthenticationAuditWhereUniqueInput[]
  update?: Prisma.AuthenticationAuditUpdateWithWhereUniqueWithoutUserInput | Prisma.AuthenticationAuditUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.AuthenticationAuditUpdateManyWithWhereWithoutUserInput | Prisma.AuthenticationAuditUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.AuthenticationAuditScalarWhereInput | Prisma.AuthenticationAuditScalarWhereInput[]
}

export type AuthenticationAuditUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.AuthenticationAuditCreateWithoutUserInput, Prisma.AuthenticationAuditUncheckedCreateWithoutUserInput> | Prisma.AuthenticationAuditCreateWithoutUserInput[] | Prisma.AuthenticationAuditUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.AuthenticationAuditCreateOrConnectWithoutUserInput | Prisma.AuthenticationAuditCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.AuthenticationAuditUpsertWithWhereUniqueWithoutUserInput | Prisma.AuthenticationAuditUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.AuthenticationAuditCreateManyUserInputEnvelope
  set?: Prisma.AuthenticationAuditWhereUniqueInput | Prisma.AuthenticationAuditWhereUniqueInput[]
  disconnect?: Prisma.AuthenticationAuditWhereUniqueInput | Prisma.AuthenticationAuditWhereUniqueInput[]
  delete?: Prisma.AuthenticationAuditWhereUniqueInput | Prisma.AuthenticationAuditWhereUniqueInput[]
  connect?: Prisma.AuthenticationAuditWhereUniqueInput | Prisma.AuthenticationAuditWhereUniqueInput[]
  update?: Prisma.AuthenticationAuditUpdateWithWhereUniqueWithoutUserInput | Prisma.AuthenticationAuditUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.AuthenticationAuditUpdateManyWithWhereWithoutUserInput | Prisma.AuthenticationAuditUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.AuthenticationAuditScalarWhereInput | Prisma.AuthenticationAuditScalarWhereInput[]
}

export type AuthenticationAuditCreateWithoutUserInput = {
  id?: string
  ipAddress?: string | null
  remotePort?: string | null
  userAgent?: string | null
  origin?: string | null
  status: $Enums.AuthenticationStatus
  createdAt?: Date | string
}

export type AuthenticationAuditUncheckedCreateWithoutUserInput = {
  id?: string
  ipAddress?: string | null
  remotePort?: string | null
  userAgent?: string | null
  origin?: string | null
  status: $Enums.AuthenticationStatus
  createdAt?: Date | string
}

export type AuthenticationAuditCreateOrConnectWithoutUserInput = {
  where: Prisma.AuthenticationAuditWhereUniqueInput
  create: Prisma.XOR<Prisma.AuthenticationAuditCreateWithoutUserInput, Prisma.AuthenticationAuditUncheckedCreateWithoutUserInput>
}

export type AuthenticationAuditCreateManyUserInputEnvelope = {
  data: Prisma.AuthenticationAuditCreateManyUserInput | Prisma.AuthenticationAuditCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type AuthenticationAuditUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.AuthenticationAuditWhereUniqueInput
  update: Prisma.XOR<Prisma.AuthenticationAuditUpdateWithoutUserInput, Prisma.AuthenticationAuditUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.AuthenticationAuditCreateWithoutUserInput, Prisma.AuthenticationAuditUncheckedCreateWithoutUserInput>
}

export type AuthenticationAuditUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.AuthenticationAuditWhereUniqueInput
  data: Prisma.XOR<Prisma.AuthenticationAuditUpdateWithoutUserInput, Prisma.AuthenticationAuditUncheckedUpdateWithoutUserInput>
}

export type AuthenticationAuditUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.AuthenticationAuditScalarWhereInput
  data: Prisma.XOR<Prisma.AuthenticationAuditUpdateManyMutationInput, Prisma.AuthenticationAuditUncheckedUpdateManyWithoutUserInput>
}

export type AuthenticationAuditScalarWhereInput = {
  AND?: Prisma.AuthenticationAuditScalarWhereInput | Prisma.AuthenticationAuditScalarWhereInput[]
  OR?: Prisma.AuthenticationAuditScalarWhereInput[]
  NOT?: Prisma.AuthenticationAuditScalarWhereInput | Prisma.AuthenticationAuditScalarWhereInput[]
  id?: Prisma.StringFilter<"AuthenticationAudit"> | string
  ipAddress?: Prisma.StringNullableFilter<"AuthenticationAudit"> | string | null
  remotePort?: Prisma.StringNullableFilter<"AuthenticationAudit"> | string | null
  userAgent?: Prisma.StringNullableFilter<"AuthenticationAudit"> | string | null
  origin?: Prisma.StringNullableFilter<"AuthenticationAudit"> | string | null
  status?: Prisma.EnumAuthenticationStatusFilter<"AuthenticationAudit"> | $Enums.AuthenticationStatus
  userId?: Prisma.IntNullableFilter<"AuthenticationAudit"> | number | null
  createdAt?: Prisma.DateTimeFilter<"AuthenticationAudit"> | Date | string
}

export type AuthenticationAuditCreateManyUserInput = {
  id?: string
  ipAddress?: string | null
  remotePort?: string | null
  userAgent?: string | null
  origin?: string | null
  status: $Enums.AuthenticationStatus
  createdAt?: Date | string
}

export type AuthenticationAuditUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  ipAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  remotePort?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userAgent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  origin?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumAuthenticationStatusFieldUpdateOperationsInput | $Enums.AuthenticationStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AuthenticationAuditUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  ipAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  remotePort?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userAgent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  origin?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumAuthenticationStatusFieldUpdateOperationsInput | $Enums.AuthenticationStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AuthenticationAuditUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  ipAddress?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  remotePort?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userAgent?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  origin?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumAuthenticationStatusFieldUpdateOperationsInput | $Enums.AuthenticationStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type AuthenticationAuditSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  ipAddress?: boolean
  remotePort?: boolean
  userAgent?: boolean
  origin?: boolean
  status?: boolean
  userId?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.AuthenticationAudit$userArgs<ExtArgs>
}, ExtArgs["result"]["authenticationAudit"]>

export type AuthenticationAuditSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  ipAddress?: boolean
  remotePort?: boolean
  userAgent?: boolean
  origin?: boolean
  status?: boolean
  userId?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.AuthenticationAudit$userArgs<ExtArgs>
}, ExtArgs["result"]["authenticationAudit"]>

export type AuthenticationAuditSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  ipAddress?: boolean
  remotePort?: boolean
  userAgent?: boolean
  origin?: boolean
  status?: boolean
  userId?: boolean
  createdAt?: boolean
  user?: boolean | Prisma.AuthenticationAudit$userArgs<ExtArgs>
}, ExtArgs["result"]["authenticationAudit"]>

export type AuthenticationAuditSelectScalar = {
  id?: boolean
  ipAddress?: boolean
  remotePort?: boolean
  userAgent?: boolean
  origin?: boolean
  status?: boolean
  userId?: boolean
  createdAt?: boolean
}

export type AuthenticationAuditOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "ipAddress" | "remotePort" | "userAgent" | "origin" | "status" | "userId" | "createdAt", ExtArgs["result"]["authenticationAudit"]>
export type AuthenticationAuditInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.AuthenticationAudit$userArgs<ExtArgs>
}
export type AuthenticationAuditIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.AuthenticationAudit$userArgs<ExtArgs>
}
export type AuthenticationAuditIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.AuthenticationAudit$userArgs<ExtArgs>
}

export type $AuthenticationAuditPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AuthenticationAudit"
  objects: {
    user: Prisma.$UserPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    ipAddress: string | null
    remotePort: string | null
    userAgent: string | null
    origin: string | null
    status: $Enums.AuthenticationStatus
    userId: number | null
    createdAt: Date
  }, ExtArgs["result"]["authenticationAudit"]>
  composites: {}
}

export type AuthenticationAuditGetPayload<S extends boolean | null | undefined | AuthenticationAuditDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AuthenticationAuditPayload, S>

export type AuthenticationAuditCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AuthenticationAuditFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AuthenticationAuditCountAggregateInputType | true
  }

export interface AuthenticationAuditDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AuthenticationAudit'], meta: { name: 'AuthenticationAudit' } }
  /**
   * Find zero or one AuthenticationAudit that matches the filter.
   * @param {AuthenticationAuditFindUniqueArgs} args - Arguments to find a AuthenticationAudit
   * @example
   * // Get one AuthenticationAudit
   * const authenticationAudit = await prisma.authenticationAudit.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AuthenticationAuditFindUniqueArgs>(args: Prisma.SelectSubset<T, AuthenticationAuditFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AuthenticationAuditClient<runtime.Types.Result.GetResult<Prisma.$AuthenticationAuditPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AuthenticationAudit that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AuthenticationAuditFindUniqueOrThrowArgs} args - Arguments to find a AuthenticationAudit
   * @example
   * // Get one AuthenticationAudit
   * const authenticationAudit = await prisma.authenticationAudit.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AuthenticationAuditFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AuthenticationAuditFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AuthenticationAuditClient<runtime.Types.Result.GetResult<Prisma.$AuthenticationAuditPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AuthenticationAudit that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuthenticationAuditFindFirstArgs} args - Arguments to find a AuthenticationAudit
   * @example
   * // Get one AuthenticationAudit
   * const authenticationAudit = await prisma.authenticationAudit.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AuthenticationAuditFindFirstArgs>(args?: Prisma.SelectSubset<T, AuthenticationAuditFindFirstArgs<ExtArgs>>): Prisma.Prisma__AuthenticationAuditClient<runtime.Types.Result.GetResult<Prisma.$AuthenticationAuditPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AuthenticationAudit that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuthenticationAuditFindFirstOrThrowArgs} args - Arguments to find a AuthenticationAudit
   * @example
   * // Get one AuthenticationAudit
   * const authenticationAudit = await prisma.authenticationAudit.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AuthenticationAuditFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AuthenticationAuditFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AuthenticationAuditClient<runtime.Types.Result.GetResult<Prisma.$AuthenticationAuditPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AuthenticationAudits that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuthenticationAuditFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AuthenticationAudits
   * const authenticationAudits = await prisma.authenticationAudit.findMany()
   * 
   * // Get first 10 AuthenticationAudits
   * const authenticationAudits = await prisma.authenticationAudit.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const authenticationAuditWithIdOnly = await prisma.authenticationAudit.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AuthenticationAuditFindManyArgs>(args?: Prisma.SelectSubset<T, AuthenticationAuditFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AuthenticationAuditPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AuthenticationAudit.
   * @param {AuthenticationAuditCreateArgs} args - Arguments to create a AuthenticationAudit.
   * @example
   * // Create one AuthenticationAudit
   * const AuthenticationAudit = await prisma.authenticationAudit.create({
   *   data: {
   *     // ... data to create a AuthenticationAudit
   *   }
   * })
   * 
   */
  create<T extends AuthenticationAuditCreateArgs>(args: Prisma.SelectSubset<T, AuthenticationAuditCreateArgs<ExtArgs>>): Prisma.Prisma__AuthenticationAuditClient<runtime.Types.Result.GetResult<Prisma.$AuthenticationAuditPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AuthenticationAudits.
   * @param {AuthenticationAuditCreateManyArgs} args - Arguments to create many AuthenticationAudits.
   * @example
   * // Create many AuthenticationAudits
   * const authenticationAudit = await prisma.authenticationAudit.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AuthenticationAuditCreateManyArgs>(args?: Prisma.SelectSubset<T, AuthenticationAuditCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AuthenticationAudits and returns the data saved in the database.
   * @param {AuthenticationAuditCreateManyAndReturnArgs} args - Arguments to create many AuthenticationAudits.
   * @example
   * // Create many AuthenticationAudits
   * const authenticationAudit = await prisma.authenticationAudit.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AuthenticationAudits and only return the `id`
   * const authenticationAuditWithIdOnly = await prisma.authenticationAudit.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AuthenticationAuditCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AuthenticationAuditCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AuthenticationAuditPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AuthenticationAudit.
   * @param {AuthenticationAuditDeleteArgs} args - Arguments to delete one AuthenticationAudit.
   * @example
   * // Delete one AuthenticationAudit
   * const AuthenticationAudit = await prisma.authenticationAudit.delete({
   *   where: {
   *     // ... filter to delete one AuthenticationAudit
   *   }
   * })
   * 
   */
  delete<T extends AuthenticationAuditDeleteArgs>(args: Prisma.SelectSubset<T, AuthenticationAuditDeleteArgs<ExtArgs>>): Prisma.Prisma__AuthenticationAuditClient<runtime.Types.Result.GetResult<Prisma.$AuthenticationAuditPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AuthenticationAudit.
   * @param {AuthenticationAuditUpdateArgs} args - Arguments to update one AuthenticationAudit.
   * @example
   * // Update one AuthenticationAudit
   * const authenticationAudit = await prisma.authenticationAudit.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AuthenticationAuditUpdateArgs>(args: Prisma.SelectSubset<T, AuthenticationAuditUpdateArgs<ExtArgs>>): Prisma.Prisma__AuthenticationAuditClient<runtime.Types.Result.GetResult<Prisma.$AuthenticationAuditPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AuthenticationAudits.
   * @param {AuthenticationAuditDeleteManyArgs} args - Arguments to filter AuthenticationAudits to delete.
   * @example
   * // Delete a few AuthenticationAudits
   * const { count } = await prisma.authenticationAudit.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AuthenticationAuditDeleteManyArgs>(args?: Prisma.SelectSubset<T, AuthenticationAuditDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AuthenticationAudits.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuthenticationAuditUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AuthenticationAudits
   * const authenticationAudit = await prisma.authenticationAudit.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AuthenticationAuditUpdateManyArgs>(args: Prisma.SelectSubset<T, AuthenticationAuditUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AuthenticationAudits and returns the data updated in the database.
   * @param {AuthenticationAuditUpdateManyAndReturnArgs} args - Arguments to update many AuthenticationAudits.
   * @example
   * // Update many AuthenticationAudits
   * const authenticationAudit = await prisma.authenticationAudit.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AuthenticationAudits and only return the `id`
   * const authenticationAuditWithIdOnly = await prisma.authenticationAudit.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AuthenticationAuditUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AuthenticationAuditUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AuthenticationAuditPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AuthenticationAudit.
   * @param {AuthenticationAuditUpsertArgs} args - Arguments to update or create a AuthenticationAudit.
   * @example
   * // Update or create a AuthenticationAudit
   * const authenticationAudit = await prisma.authenticationAudit.upsert({
   *   create: {
   *     // ... data to create a AuthenticationAudit
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AuthenticationAudit we want to update
   *   }
   * })
   */
  upsert<T extends AuthenticationAuditUpsertArgs>(args: Prisma.SelectSubset<T, AuthenticationAuditUpsertArgs<ExtArgs>>): Prisma.Prisma__AuthenticationAuditClient<runtime.Types.Result.GetResult<Prisma.$AuthenticationAuditPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AuthenticationAudits.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuthenticationAuditCountArgs} args - Arguments to filter AuthenticationAudits to count.
   * @example
   * // Count the number of AuthenticationAudits
   * const count = await prisma.authenticationAudit.count({
   *   where: {
   *     // ... the filter for the AuthenticationAudits we want to count
   *   }
   * })
  **/
  count<T extends AuthenticationAuditCountArgs>(
    args?: Prisma.Subset<T, AuthenticationAuditCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AuthenticationAuditCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AuthenticationAudit.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuthenticationAuditAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AuthenticationAuditAggregateArgs>(args: Prisma.Subset<T, AuthenticationAuditAggregateArgs>): Prisma.PrismaPromise<GetAuthenticationAuditAggregateType<T>>

  /**
   * Group by AuthenticationAudit.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuthenticationAuditGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AuthenticationAuditGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AuthenticationAuditGroupByArgs['orderBy'] }
      : { orderBy?: AuthenticationAuditGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AuthenticationAuditGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAuthenticationAuditGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AuthenticationAudit model
 */
readonly fields: AuthenticationAuditFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AuthenticationAudit.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AuthenticationAuditClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.AuthenticationAudit$userArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AuthenticationAudit$userArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AuthenticationAudit model
 */
export interface AuthenticationAuditFieldRefs {
  readonly id: Prisma.FieldRef<"AuthenticationAudit", 'String'>
  readonly ipAddress: Prisma.FieldRef<"AuthenticationAudit", 'String'>
  readonly remotePort: Prisma.FieldRef<"AuthenticationAudit", 'String'>
  readonly userAgent: Prisma.FieldRef<"AuthenticationAudit", 'String'>
  readonly origin: Prisma.FieldRef<"AuthenticationAudit", 'String'>
  readonly status: Prisma.FieldRef<"AuthenticationAudit", 'AuthenticationStatus'>
  readonly userId: Prisma.FieldRef<"AuthenticationAudit", 'Int'>
  readonly createdAt: Prisma.FieldRef<"AuthenticationAudit", 'DateTime'>
}
    

// Custom InputTypes
/**
 * AuthenticationAudit findUnique
 */
export type AuthenticationAuditFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthenticationAudit
   */
  select?: Prisma.AuthenticationAuditSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthenticationAudit
   */
  omit?: Prisma.AuthenticationAuditOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthenticationAuditInclude<ExtArgs> | null
  /**
   * Filter, which AuthenticationAudit to fetch.
   */
  where: Prisma.AuthenticationAuditWhereUniqueInput
}

/**
 * AuthenticationAudit findUniqueOrThrow
 */
export type AuthenticationAuditFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthenticationAudit
   */
  select?: Prisma.AuthenticationAuditSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthenticationAudit
   */
  omit?: Prisma.AuthenticationAuditOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthenticationAuditInclude<ExtArgs> | null
  /**
   * Filter, which AuthenticationAudit to fetch.
   */
  where: Prisma.AuthenticationAuditWhereUniqueInput
}

/**
 * AuthenticationAudit findFirst
 */
export type AuthenticationAuditFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthenticationAudit
   */
  select?: Prisma.AuthenticationAuditSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthenticationAudit
   */
  omit?: Prisma.AuthenticationAuditOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthenticationAuditInclude<ExtArgs> | null
  /**
   * Filter, which AuthenticationAudit to fetch.
   */
  where?: Prisma.AuthenticationAuditWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AuthenticationAudits to fetch.
   */
  orderBy?: Prisma.AuthenticationAuditOrderByWithRelationInput | Prisma.AuthenticationAuditOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AuthenticationAudits.
   */
  cursor?: Prisma.AuthenticationAuditWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AuthenticationAudits from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AuthenticationAudits.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AuthenticationAudits.
   */
  distinct?: Prisma.AuthenticationAuditScalarFieldEnum | Prisma.AuthenticationAuditScalarFieldEnum[]
}

/**
 * AuthenticationAudit findFirstOrThrow
 */
export type AuthenticationAuditFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthenticationAudit
   */
  select?: Prisma.AuthenticationAuditSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthenticationAudit
   */
  omit?: Prisma.AuthenticationAuditOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthenticationAuditInclude<ExtArgs> | null
  /**
   * Filter, which AuthenticationAudit to fetch.
   */
  where?: Prisma.AuthenticationAuditWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AuthenticationAudits to fetch.
   */
  orderBy?: Prisma.AuthenticationAuditOrderByWithRelationInput | Prisma.AuthenticationAuditOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AuthenticationAudits.
   */
  cursor?: Prisma.AuthenticationAuditWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AuthenticationAudits from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AuthenticationAudits.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AuthenticationAudits.
   */
  distinct?: Prisma.AuthenticationAuditScalarFieldEnum | Prisma.AuthenticationAuditScalarFieldEnum[]
}

/**
 * AuthenticationAudit findMany
 */
export type AuthenticationAuditFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthenticationAudit
   */
  select?: Prisma.AuthenticationAuditSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthenticationAudit
   */
  omit?: Prisma.AuthenticationAuditOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthenticationAuditInclude<ExtArgs> | null
  /**
   * Filter, which AuthenticationAudits to fetch.
   */
  where?: Prisma.AuthenticationAuditWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AuthenticationAudits to fetch.
   */
  orderBy?: Prisma.AuthenticationAuditOrderByWithRelationInput | Prisma.AuthenticationAuditOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AuthenticationAudits.
   */
  cursor?: Prisma.AuthenticationAuditWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AuthenticationAudits from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AuthenticationAudits.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AuthenticationAudits.
   */
  distinct?: Prisma.AuthenticationAuditScalarFieldEnum | Prisma.AuthenticationAuditScalarFieldEnum[]
}

/**
 * AuthenticationAudit create
 */
export type AuthenticationAuditCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthenticationAudit
   */
  select?: Prisma.AuthenticationAuditSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthenticationAudit
   */
  omit?: Prisma.AuthenticationAuditOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthenticationAuditInclude<ExtArgs> | null
  /**
   * The data needed to create a AuthenticationAudit.
   */
  data: Prisma.XOR<Prisma.AuthenticationAuditCreateInput, Prisma.AuthenticationAuditUncheckedCreateInput>
}

/**
 * AuthenticationAudit createMany
 */
export type AuthenticationAuditCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AuthenticationAudits.
   */
  data: Prisma.AuthenticationAuditCreateManyInput | Prisma.AuthenticationAuditCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AuthenticationAudit createManyAndReturn
 */
export type AuthenticationAuditCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthenticationAudit
   */
  select?: Prisma.AuthenticationAuditSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AuthenticationAudit
   */
  omit?: Prisma.AuthenticationAuditOmit<ExtArgs> | null
  /**
   * The data used to create many AuthenticationAudits.
   */
  data: Prisma.AuthenticationAuditCreateManyInput | Prisma.AuthenticationAuditCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthenticationAuditIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * AuthenticationAudit update
 */
export type AuthenticationAuditUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthenticationAudit
   */
  select?: Prisma.AuthenticationAuditSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthenticationAudit
   */
  omit?: Prisma.AuthenticationAuditOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthenticationAuditInclude<ExtArgs> | null
  /**
   * The data needed to update a AuthenticationAudit.
   */
  data: Prisma.XOR<Prisma.AuthenticationAuditUpdateInput, Prisma.AuthenticationAuditUncheckedUpdateInput>
  /**
   * Choose, which AuthenticationAudit to update.
   */
  where: Prisma.AuthenticationAuditWhereUniqueInput
}

/**
 * AuthenticationAudit updateMany
 */
export type AuthenticationAuditUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AuthenticationAudits.
   */
  data: Prisma.XOR<Prisma.AuthenticationAuditUpdateManyMutationInput, Prisma.AuthenticationAuditUncheckedUpdateManyInput>
  /**
   * Filter which AuthenticationAudits to update
   */
  where?: Prisma.AuthenticationAuditWhereInput
  /**
   * Limit how many AuthenticationAudits to update.
   */
  limit?: number
}

/**
 * AuthenticationAudit updateManyAndReturn
 */
export type AuthenticationAuditUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthenticationAudit
   */
  select?: Prisma.AuthenticationAuditSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AuthenticationAudit
   */
  omit?: Prisma.AuthenticationAuditOmit<ExtArgs> | null
  /**
   * The data used to update AuthenticationAudits.
   */
  data: Prisma.XOR<Prisma.AuthenticationAuditUpdateManyMutationInput, Prisma.AuthenticationAuditUncheckedUpdateManyInput>
  /**
   * Filter which AuthenticationAudits to update
   */
  where?: Prisma.AuthenticationAuditWhereInput
  /**
   * Limit how many AuthenticationAudits to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthenticationAuditIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * AuthenticationAudit upsert
 */
export type AuthenticationAuditUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthenticationAudit
   */
  select?: Prisma.AuthenticationAuditSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthenticationAudit
   */
  omit?: Prisma.AuthenticationAuditOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthenticationAuditInclude<ExtArgs> | null
  /**
   * The filter to search for the AuthenticationAudit to update in case it exists.
   */
  where: Prisma.AuthenticationAuditWhereUniqueInput
  /**
   * In case the AuthenticationAudit found by the `where` argument doesn't exist, create a new AuthenticationAudit with this data.
   */
  create: Prisma.XOR<Prisma.AuthenticationAuditCreateInput, Prisma.AuthenticationAuditUncheckedCreateInput>
  /**
   * In case the AuthenticationAudit was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AuthenticationAuditUpdateInput, Prisma.AuthenticationAuditUncheckedUpdateInput>
}

/**
 * AuthenticationAudit delete
 */
export type AuthenticationAuditDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthenticationAudit
   */
  select?: Prisma.AuthenticationAuditSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthenticationAudit
   */
  omit?: Prisma.AuthenticationAuditOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthenticationAuditInclude<ExtArgs> | null
  /**
   * Filter which AuthenticationAudit to delete.
   */
  where: Prisma.AuthenticationAuditWhereUniqueInput
}

/**
 * AuthenticationAudit deleteMany
 */
export type AuthenticationAuditDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AuthenticationAudits to delete
   */
  where?: Prisma.AuthenticationAuditWhereInput
  /**
   * Limit how many AuthenticationAudits to delete.
   */
  limit?: number
}

/**
 * AuthenticationAudit.user
 */
export type AuthenticationAudit$userArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
}

/**
 * AuthenticationAudit without action
 */
export type AuthenticationAuditDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthenticationAudit
   */
  select?: Prisma.AuthenticationAuditSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthenticationAudit
   */
  omit?: Prisma.AuthenticationAuditOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthenticationAuditInclude<ExtArgs> | null
}
