
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ModerationReport` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model ModerationReport
 * 
 */
export type ModerationReportModel = runtime.Types.Result.DefaultSelection<Prisma.$ModerationReportPayload>

export type AggregateModerationReport = {
  _count: ModerationReportCountAggregateOutputType | null
  _avg: ModerationReportAvgAggregateOutputType | null
  _sum: ModerationReportSumAggregateOutputType | null
  _min: ModerationReportMinAggregateOutputType | null
  _max: ModerationReportMaxAggregateOutputType | null
}

export type ModerationReportAvgAggregateOutputType = {
  id: number | null
  reporterId: number | null
  placeId: number | null
}

export type ModerationReportSumAggregateOutputType = {
  id: number | null
  reporterId: number | null
  placeId: number | null
}

export type ModerationReportMinAggregateOutputType = {
  id: number | null
  publicId: string | null
  reason: string | null
  status: $Enums.ModerationReportStatus | null
  reporterId: number | null
  placeId: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ModerationReportMaxAggregateOutputType = {
  id: number | null
  publicId: string | null
  reason: string | null
  status: $Enums.ModerationReportStatus | null
  reporterId: number | null
  placeId: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ModerationReportCountAggregateOutputType = {
  id: number
  publicId: number
  reason: number
  status: number
  reporterId: number
  placeId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ModerationReportAvgAggregateInputType = {
  id?: true
  reporterId?: true
  placeId?: true
}

export type ModerationReportSumAggregateInputType = {
  id?: true
  reporterId?: true
  placeId?: true
}

export type ModerationReportMinAggregateInputType = {
  id?: true
  publicId?: true
  reason?: true
  status?: true
  reporterId?: true
  placeId?: true
  createdAt?: true
  updatedAt?: true
}

export type ModerationReportMaxAggregateInputType = {
  id?: true
  publicId?: true
  reason?: true
  status?: true
  reporterId?: true
  placeId?: true
  createdAt?: true
  updatedAt?: true
}

export type ModerationReportCountAggregateInputType = {
  id?: true
  publicId?: true
  reason?: true
  status?: true
  reporterId?: true
  placeId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ModerationReportAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ModerationReport to aggregate.
   */
  where?: Prisma.ModerationReportWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ModerationReports to fetch.
   */
  orderBy?: Prisma.ModerationReportOrderByWithRelationInput | Prisma.ModerationReportOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ModerationReportWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ModerationReports from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ModerationReports.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ModerationReports
  **/
  _count?: true | ModerationReportCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ModerationReportAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ModerationReportSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ModerationReportMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ModerationReportMaxAggregateInputType
}

export type GetModerationReportAggregateType<T extends ModerationReportAggregateArgs> = {
      [P in keyof T & keyof AggregateModerationReport]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateModerationReport[P]>
    : Prisma.GetScalarType<T[P], AggregateModerationReport[P]>
}




export type ModerationReportGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ModerationReportWhereInput
  orderBy?: Prisma.ModerationReportOrderByWithAggregationInput | Prisma.ModerationReportOrderByWithAggregationInput[]
  by: Prisma.ModerationReportScalarFieldEnum[] | Prisma.ModerationReportScalarFieldEnum
  having?: Prisma.ModerationReportScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ModerationReportCountAggregateInputType | true
  _avg?: ModerationReportAvgAggregateInputType
  _sum?: ModerationReportSumAggregateInputType
  _min?: ModerationReportMinAggregateInputType
  _max?: ModerationReportMaxAggregateInputType
}

export type ModerationReportGroupByOutputType = {
  id: number
  publicId: string
  reason: string
  status: $Enums.ModerationReportStatus
  reporterId: number
  placeId: number | null
  createdAt: Date
  updatedAt: Date
  _count: ModerationReportCountAggregateOutputType | null
  _avg: ModerationReportAvgAggregateOutputType | null
  _sum: ModerationReportSumAggregateOutputType | null
  _min: ModerationReportMinAggregateOutputType | null
  _max: ModerationReportMaxAggregateOutputType | null
}

export type GetModerationReportGroupByPayload<T extends ModerationReportGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ModerationReportGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ModerationReportGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ModerationReportGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ModerationReportGroupByOutputType[P]>
      }
    >
  >



export type ModerationReportWhereInput = {
  AND?: Prisma.ModerationReportWhereInput | Prisma.ModerationReportWhereInput[]
  OR?: Prisma.ModerationReportWhereInput[]
  NOT?: Prisma.ModerationReportWhereInput | Prisma.ModerationReportWhereInput[]
  id?: Prisma.IntFilter<"ModerationReport"> | number
  publicId?: Prisma.StringFilter<"ModerationReport"> | string
  reason?: Prisma.StringFilter<"ModerationReport"> | string
  status?: Prisma.EnumModerationReportStatusFilter<"ModerationReport"> | $Enums.ModerationReportStatus
  reporterId?: Prisma.IntFilter<"ModerationReport"> | number
  placeId?: Prisma.IntNullableFilter<"ModerationReport"> | number | null
  createdAt?: Prisma.DateTimeFilter<"ModerationReport"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ModerationReport"> | Date | string
  reporter?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  place?: Prisma.XOR<Prisma.PlaceNullableScalarRelationFilter, Prisma.PlaceWhereInput> | null
}

export type ModerationReportOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  publicId?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  status?: Prisma.SortOrder
  reporterId?: Prisma.SortOrder
  placeId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  reporter?: Prisma.UserOrderByWithRelationInput
  place?: Prisma.PlaceOrderByWithRelationInput
}

export type ModerationReportWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  publicId?: string
  AND?: Prisma.ModerationReportWhereInput | Prisma.ModerationReportWhereInput[]
  OR?: Prisma.ModerationReportWhereInput[]
  NOT?: Prisma.ModerationReportWhereInput | Prisma.ModerationReportWhereInput[]
  reason?: Prisma.StringFilter<"ModerationReport"> | string
  status?: Prisma.EnumModerationReportStatusFilter<"ModerationReport"> | $Enums.ModerationReportStatus
  reporterId?: Prisma.IntFilter<"ModerationReport"> | number
  placeId?: Prisma.IntNullableFilter<"ModerationReport"> | number | null
  createdAt?: Prisma.DateTimeFilter<"ModerationReport"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ModerationReport"> | Date | string
  reporter?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  place?: Prisma.XOR<Prisma.PlaceNullableScalarRelationFilter, Prisma.PlaceWhereInput> | null
}, "id" | "publicId">

export type ModerationReportOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  publicId?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  status?: Prisma.SortOrder
  reporterId?: Prisma.SortOrder
  placeId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ModerationReportCountOrderByAggregateInput
  _avg?: Prisma.ModerationReportAvgOrderByAggregateInput
  _max?: Prisma.ModerationReportMaxOrderByAggregateInput
  _min?: Prisma.ModerationReportMinOrderByAggregateInput
  _sum?: Prisma.ModerationReportSumOrderByAggregateInput
}

export type ModerationReportScalarWhereWithAggregatesInput = {
  AND?: Prisma.ModerationReportScalarWhereWithAggregatesInput | Prisma.ModerationReportScalarWhereWithAggregatesInput[]
  OR?: Prisma.ModerationReportScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ModerationReportScalarWhereWithAggregatesInput | Prisma.ModerationReportScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"ModerationReport"> | number
  publicId?: Prisma.StringWithAggregatesFilter<"ModerationReport"> | string
  reason?: Prisma.StringWithAggregatesFilter<"ModerationReport"> | string
  status?: Prisma.EnumModerationReportStatusWithAggregatesFilter<"ModerationReport"> | $Enums.ModerationReportStatus
  reporterId?: Prisma.IntWithAggregatesFilter<"ModerationReport"> | number
  placeId?: Prisma.IntNullableWithAggregatesFilter<"ModerationReport"> | number | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ModerationReport"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"ModerationReport"> | Date | string
}

export type ModerationReportCreateInput = {
  publicId?: string
  reason: string
  status?: $Enums.ModerationReportStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  reporter: Prisma.UserCreateNestedOneWithoutModerationReportsInput
  place?: Prisma.PlaceCreateNestedOneWithoutReportsInput
}

export type ModerationReportUncheckedCreateInput = {
  id?: number
  publicId?: string
  reason: string
  status?: $Enums.ModerationReportStatus
  reporterId: number
  placeId?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ModerationReportUpdateInput = {
  publicId?: Prisma.StringFieldUpdateOperationsInput | string
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumModerationReportStatusFieldUpdateOperationsInput | $Enums.ModerationReportStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  reporter?: Prisma.UserUpdateOneRequiredWithoutModerationReportsNestedInput
  place?: Prisma.PlaceUpdateOneWithoutReportsNestedInput
}

export type ModerationReportUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  publicId?: Prisma.StringFieldUpdateOperationsInput | string
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumModerationReportStatusFieldUpdateOperationsInput | $Enums.ModerationReportStatus
  reporterId?: Prisma.IntFieldUpdateOperationsInput | number
  placeId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ModerationReportCreateManyInput = {
  id?: number
  publicId?: string
  reason: string
  status?: $Enums.ModerationReportStatus
  reporterId: number
  placeId?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ModerationReportUpdateManyMutationInput = {
  publicId?: Prisma.StringFieldUpdateOperationsInput | string
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumModerationReportStatusFieldUpdateOperationsInput | $Enums.ModerationReportStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ModerationReportUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  publicId?: Prisma.StringFieldUpdateOperationsInput | string
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumModerationReportStatusFieldUpdateOperationsInput | $Enums.ModerationReportStatus
  reporterId?: Prisma.IntFieldUpdateOperationsInput | number
  placeId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ModerationReportListRelationFilter = {
  every?: Prisma.ModerationReportWhereInput
  some?: Prisma.ModerationReportWhereInput
  none?: Prisma.ModerationReportWhereInput
}

export type ModerationReportOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ModerationReportCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  publicId?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  status?: Prisma.SortOrder
  reporterId?: Prisma.SortOrder
  placeId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ModerationReportAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  reporterId?: Prisma.SortOrder
  placeId?: Prisma.SortOrder
}

export type ModerationReportMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  publicId?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  status?: Prisma.SortOrder
  reporterId?: Prisma.SortOrder
  placeId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ModerationReportMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  publicId?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  status?: Prisma.SortOrder
  reporterId?: Prisma.SortOrder
  placeId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ModerationReportSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  reporterId?: Prisma.SortOrder
  placeId?: Prisma.SortOrder
}

export type ModerationReportCreateNestedManyWithoutPlaceInput = {
  create?: Prisma.XOR<Prisma.ModerationReportCreateWithoutPlaceInput, Prisma.ModerationReportUncheckedCreateWithoutPlaceInput> | Prisma.ModerationReportCreateWithoutPlaceInput[] | Prisma.ModerationReportUncheckedCreateWithoutPlaceInput[]
  connectOrCreate?: Prisma.ModerationReportCreateOrConnectWithoutPlaceInput | Prisma.ModerationReportCreateOrConnectWithoutPlaceInput[]
  createMany?: Prisma.ModerationReportCreateManyPlaceInputEnvelope
  connect?: Prisma.ModerationReportWhereUniqueInput | Prisma.ModerationReportWhereUniqueInput[]
}

export type ModerationReportUncheckedCreateNestedManyWithoutPlaceInput = {
  create?: Prisma.XOR<Prisma.ModerationReportCreateWithoutPlaceInput, Prisma.ModerationReportUncheckedCreateWithoutPlaceInput> | Prisma.ModerationReportCreateWithoutPlaceInput[] | Prisma.ModerationReportUncheckedCreateWithoutPlaceInput[]
  connectOrCreate?: Prisma.ModerationReportCreateOrConnectWithoutPlaceInput | Prisma.ModerationReportCreateOrConnectWithoutPlaceInput[]
  createMany?: Prisma.ModerationReportCreateManyPlaceInputEnvelope
  connect?: Prisma.ModerationReportWhereUniqueInput | Prisma.ModerationReportWhereUniqueInput[]
}

export type ModerationReportUpdateManyWithoutPlaceNestedInput = {
  create?: Prisma.XOR<Prisma.ModerationReportCreateWithoutPlaceInput, Prisma.ModerationReportUncheckedCreateWithoutPlaceInput> | Prisma.ModerationReportCreateWithoutPlaceInput[] | Prisma.ModerationReportUncheckedCreateWithoutPlaceInput[]
  connectOrCreate?: Prisma.ModerationReportCreateOrConnectWithoutPlaceInput | Prisma.ModerationReportCreateOrConnectWithoutPlaceInput[]
  upsert?: Prisma.ModerationReportUpsertWithWhereUniqueWithoutPlaceInput | Prisma.ModerationReportUpsertWithWhereUniqueWithoutPlaceInput[]
  createMany?: Prisma.ModerationReportCreateManyPlaceInputEnvelope
  set?: Prisma.ModerationReportWhereUniqueInput | Prisma.ModerationReportWhereUniqueInput[]
  disconnect?: Prisma.ModerationReportWhereUniqueInput | Prisma.ModerationReportWhereUniqueInput[]
  delete?: Prisma.ModerationReportWhereUniqueInput | Prisma.ModerationReportWhereUniqueInput[]
  connect?: Prisma.ModerationReportWhereUniqueInput | Prisma.ModerationReportWhereUniqueInput[]
  update?: Prisma.ModerationReportUpdateWithWhereUniqueWithoutPlaceInput | Prisma.ModerationReportUpdateWithWhereUniqueWithoutPlaceInput[]
  updateMany?: Prisma.ModerationReportUpdateManyWithWhereWithoutPlaceInput | Prisma.ModerationReportUpdateManyWithWhereWithoutPlaceInput[]
  deleteMany?: Prisma.ModerationReportScalarWhereInput | Prisma.ModerationReportScalarWhereInput[]
}

export type ModerationReportUncheckedUpdateManyWithoutPlaceNestedInput = {
  create?: Prisma.XOR<Prisma.ModerationReportCreateWithoutPlaceInput, Prisma.ModerationReportUncheckedCreateWithoutPlaceInput> | Prisma.ModerationReportCreateWithoutPlaceInput[] | Prisma.ModerationReportUncheckedCreateWithoutPlaceInput[]
  connectOrCreate?: Prisma.ModerationReportCreateOrConnectWithoutPlaceInput | Prisma.ModerationReportCreateOrConnectWithoutPlaceInput[]
  upsert?: Prisma.ModerationReportUpsertWithWhereUniqueWithoutPlaceInput | Prisma.ModerationReportUpsertWithWhereUniqueWithoutPlaceInput[]
  createMany?: Prisma.ModerationReportCreateManyPlaceInputEnvelope
  set?: Prisma.ModerationReportWhereUniqueInput | Prisma.ModerationReportWhereUniqueInput[]
  disconnect?: Prisma.ModerationReportWhereUniqueInput | Prisma.ModerationReportWhereUniqueInput[]
  delete?: Prisma.ModerationReportWhereUniqueInput | Prisma.ModerationReportWhereUniqueInput[]
  connect?: Prisma.ModerationReportWhereUniqueInput | Prisma.ModerationReportWhereUniqueInput[]
  update?: Prisma.ModerationReportUpdateWithWhereUniqueWithoutPlaceInput | Prisma.ModerationReportUpdateWithWhereUniqueWithoutPlaceInput[]
  updateMany?: Prisma.ModerationReportUpdateManyWithWhereWithoutPlaceInput | Prisma.ModerationReportUpdateManyWithWhereWithoutPlaceInput[]
  deleteMany?: Prisma.ModerationReportScalarWhereInput | Prisma.ModerationReportScalarWhereInput[]
}

export type EnumModerationReportStatusFieldUpdateOperationsInput = {
  set?: $Enums.ModerationReportStatus
}

export type ModerationReportCreateNestedManyWithoutReporterInput = {
  create?: Prisma.XOR<Prisma.ModerationReportCreateWithoutReporterInput, Prisma.ModerationReportUncheckedCreateWithoutReporterInput> | Prisma.ModerationReportCreateWithoutReporterInput[] | Prisma.ModerationReportUncheckedCreateWithoutReporterInput[]
  connectOrCreate?: Prisma.ModerationReportCreateOrConnectWithoutReporterInput | Prisma.ModerationReportCreateOrConnectWithoutReporterInput[]
  createMany?: Prisma.ModerationReportCreateManyReporterInputEnvelope
  connect?: Prisma.ModerationReportWhereUniqueInput | Prisma.ModerationReportWhereUniqueInput[]
}

export type ModerationReportUncheckedCreateNestedManyWithoutReporterInput = {
  create?: Prisma.XOR<Prisma.ModerationReportCreateWithoutReporterInput, Prisma.ModerationReportUncheckedCreateWithoutReporterInput> | Prisma.ModerationReportCreateWithoutReporterInput[] | Prisma.ModerationReportUncheckedCreateWithoutReporterInput[]
  connectOrCreate?: Prisma.ModerationReportCreateOrConnectWithoutReporterInput | Prisma.ModerationReportCreateOrConnectWithoutReporterInput[]
  createMany?: Prisma.ModerationReportCreateManyReporterInputEnvelope
  connect?: Prisma.ModerationReportWhereUniqueInput | Prisma.ModerationReportWhereUniqueInput[]
}

export type ModerationReportUpdateManyWithoutReporterNestedInput = {
  create?: Prisma.XOR<Prisma.ModerationReportCreateWithoutReporterInput, Prisma.ModerationReportUncheckedCreateWithoutReporterInput> | Prisma.ModerationReportCreateWithoutReporterInput[] | Prisma.ModerationReportUncheckedCreateWithoutReporterInput[]
  connectOrCreate?: Prisma.ModerationReportCreateOrConnectWithoutReporterInput | Prisma.ModerationReportCreateOrConnectWithoutReporterInput[]
  upsert?: Prisma.ModerationReportUpsertWithWhereUniqueWithoutReporterInput | Prisma.ModerationReportUpsertWithWhereUniqueWithoutReporterInput[]
  createMany?: Prisma.ModerationReportCreateManyReporterInputEnvelope
  set?: Prisma.ModerationReportWhereUniqueInput | Prisma.ModerationReportWhereUniqueInput[]
  disconnect?: Prisma.ModerationReportWhereUniqueInput | Prisma.ModerationReportWhereUniqueInput[]
  delete?: Prisma.ModerationReportWhereUniqueInput | Prisma.ModerationReportWhereUniqueInput[]
  connect?: Prisma.ModerationReportWhereUniqueInput | Prisma.ModerationReportWhereUniqueInput[]
  update?: Prisma.ModerationReportUpdateWithWhereUniqueWithoutReporterInput | Prisma.ModerationReportUpdateWithWhereUniqueWithoutReporterInput[]
  updateMany?: Prisma.ModerationReportUpdateManyWithWhereWithoutReporterInput | Prisma.ModerationReportUpdateManyWithWhereWithoutReporterInput[]
  deleteMany?: Prisma.ModerationReportScalarWhereInput | Prisma.ModerationReportScalarWhereInput[]
}

export type ModerationReportUncheckedUpdateManyWithoutReporterNestedInput = {
  create?: Prisma.XOR<Prisma.ModerationReportCreateWithoutReporterInput, Prisma.ModerationReportUncheckedCreateWithoutReporterInput> | Prisma.ModerationReportCreateWithoutReporterInput[] | Prisma.ModerationReportUncheckedCreateWithoutReporterInput[]
  connectOrCreate?: Prisma.ModerationReportCreateOrConnectWithoutReporterInput | Prisma.ModerationReportCreateOrConnectWithoutReporterInput[]
  upsert?: Prisma.ModerationReportUpsertWithWhereUniqueWithoutReporterInput | Prisma.ModerationReportUpsertWithWhereUniqueWithoutReporterInput[]
  createMany?: Prisma.ModerationReportCreateManyReporterInputEnvelope
  set?: Prisma.ModerationReportWhereUniqueInput | Prisma.ModerationReportWhereUniqueInput[]
  disconnect?: Prisma.ModerationReportWhereUniqueInput | Prisma.ModerationReportWhereUniqueInput[]
  delete?: Prisma.ModerationReportWhereUniqueInput | Prisma.ModerationReportWhereUniqueInput[]
  connect?: Prisma.ModerationReportWhereUniqueInput | Prisma.ModerationReportWhereUniqueInput[]
  update?: Prisma.ModerationReportUpdateWithWhereUniqueWithoutReporterInput | Prisma.ModerationReportUpdateWithWhereUniqueWithoutReporterInput[]
  updateMany?: Prisma.ModerationReportUpdateManyWithWhereWithoutReporterInput | Prisma.ModerationReportUpdateManyWithWhereWithoutReporterInput[]
  deleteMany?: Prisma.ModerationReportScalarWhereInput | Prisma.ModerationReportScalarWhereInput[]
}

export type ModerationReportCreateWithoutPlaceInput = {
  publicId?: string
  reason: string
  status?: $Enums.ModerationReportStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  reporter: Prisma.UserCreateNestedOneWithoutModerationReportsInput
}

export type ModerationReportUncheckedCreateWithoutPlaceInput = {
  id?: number
  publicId?: string
  reason: string
  status?: $Enums.ModerationReportStatus
  reporterId: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ModerationReportCreateOrConnectWithoutPlaceInput = {
  where: Prisma.ModerationReportWhereUniqueInput
  create: Prisma.XOR<Prisma.ModerationReportCreateWithoutPlaceInput, Prisma.ModerationReportUncheckedCreateWithoutPlaceInput>
}

export type ModerationReportCreateManyPlaceInputEnvelope = {
  data: Prisma.ModerationReportCreateManyPlaceInput | Prisma.ModerationReportCreateManyPlaceInput[]
  skipDuplicates?: boolean
}

export type ModerationReportUpsertWithWhereUniqueWithoutPlaceInput = {
  where: Prisma.ModerationReportWhereUniqueInput
  update: Prisma.XOR<Prisma.ModerationReportUpdateWithoutPlaceInput, Prisma.ModerationReportUncheckedUpdateWithoutPlaceInput>
  create: Prisma.XOR<Prisma.ModerationReportCreateWithoutPlaceInput, Prisma.ModerationReportUncheckedCreateWithoutPlaceInput>
}

export type ModerationReportUpdateWithWhereUniqueWithoutPlaceInput = {
  where: Prisma.ModerationReportWhereUniqueInput
  data: Prisma.XOR<Prisma.ModerationReportUpdateWithoutPlaceInput, Prisma.ModerationReportUncheckedUpdateWithoutPlaceInput>
}

export type ModerationReportUpdateManyWithWhereWithoutPlaceInput = {
  where: Prisma.ModerationReportScalarWhereInput
  data: Prisma.XOR<Prisma.ModerationReportUpdateManyMutationInput, Prisma.ModerationReportUncheckedUpdateManyWithoutPlaceInput>
}

export type ModerationReportScalarWhereInput = {
  AND?: Prisma.ModerationReportScalarWhereInput | Prisma.ModerationReportScalarWhereInput[]
  OR?: Prisma.ModerationReportScalarWhereInput[]
  NOT?: Prisma.ModerationReportScalarWhereInput | Prisma.ModerationReportScalarWhereInput[]
  id?: Prisma.IntFilter<"ModerationReport"> | number
  publicId?: Prisma.StringFilter<"ModerationReport"> | string
  reason?: Prisma.StringFilter<"ModerationReport"> | string
  status?: Prisma.EnumModerationReportStatusFilter<"ModerationReport"> | $Enums.ModerationReportStatus
  reporterId?: Prisma.IntFilter<"ModerationReport"> | number
  placeId?: Prisma.IntNullableFilter<"ModerationReport"> | number | null
  createdAt?: Prisma.DateTimeFilter<"ModerationReport"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ModerationReport"> | Date | string
}

export type ModerationReportCreateWithoutReporterInput = {
  publicId?: string
  reason: string
  status?: $Enums.ModerationReportStatus
  createdAt?: Date | string
  updatedAt?: Date | string
  place?: Prisma.PlaceCreateNestedOneWithoutReportsInput
}

export type ModerationReportUncheckedCreateWithoutReporterInput = {
  id?: number
  publicId?: string
  reason: string
  status?: $Enums.ModerationReportStatus
  placeId?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ModerationReportCreateOrConnectWithoutReporterInput = {
  where: Prisma.ModerationReportWhereUniqueInput
  create: Prisma.XOR<Prisma.ModerationReportCreateWithoutReporterInput, Prisma.ModerationReportUncheckedCreateWithoutReporterInput>
}

export type ModerationReportCreateManyReporterInputEnvelope = {
  data: Prisma.ModerationReportCreateManyReporterInput | Prisma.ModerationReportCreateManyReporterInput[]
  skipDuplicates?: boolean
}

export type ModerationReportUpsertWithWhereUniqueWithoutReporterInput = {
  where: Prisma.ModerationReportWhereUniqueInput
  update: Prisma.XOR<Prisma.ModerationReportUpdateWithoutReporterInput, Prisma.ModerationReportUncheckedUpdateWithoutReporterInput>
  create: Prisma.XOR<Prisma.ModerationReportCreateWithoutReporterInput, Prisma.ModerationReportUncheckedCreateWithoutReporterInput>
}

export type ModerationReportUpdateWithWhereUniqueWithoutReporterInput = {
  where: Prisma.ModerationReportWhereUniqueInput
  data: Prisma.XOR<Prisma.ModerationReportUpdateWithoutReporterInput, Prisma.ModerationReportUncheckedUpdateWithoutReporterInput>
}

export type ModerationReportUpdateManyWithWhereWithoutReporterInput = {
  where: Prisma.ModerationReportScalarWhereInput
  data: Prisma.XOR<Prisma.ModerationReportUpdateManyMutationInput, Prisma.ModerationReportUncheckedUpdateManyWithoutReporterInput>
}

export type ModerationReportCreateManyPlaceInput = {
  id?: number
  publicId?: string
  reason: string
  status?: $Enums.ModerationReportStatus
  reporterId: number
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ModerationReportUpdateWithoutPlaceInput = {
  publicId?: Prisma.StringFieldUpdateOperationsInput | string
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumModerationReportStatusFieldUpdateOperationsInput | $Enums.ModerationReportStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  reporter?: Prisma.UserUpdateOneRequiredWithoutModerationReportsNestedInput
}

export type ModerationReportUncheckedUpdateWithoutPlaceInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  publicId?: Prisma.StringFieldUpdateOperationsInput | string
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumModerationReportStatusFieldUpdateOperationsInput | $Enums.ModerationReportStatus
  reporterId?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ModerationReportUncheckedUpdateManyWithoutPlaceInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  publicId?: Prisma.StringFieldUpdateOperationsInput | string
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumModerationReportStatusFieldUpdateOperationsInput | $Enums.ModerationReportStatus
  reporterId?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ModerationReportCreateManyReporterInput = {
  id?: number
  publicId?: string
  reason: string
  status?: $Enums.ModerationReportStatus
  placeId?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ModerationReportUpdateWithoutReporterInput = {
  publicId?: Prisma.StringFieldUpdateOperationsInput | string
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumModerationReportStatusFieldUpdateOperationsInput | $Enums.ModerationReportStatus
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  place?: Prisma.PlaceUpdateOneWithoutReportsNestedInput
}

export type ModerationReportUncheckedUpdateWithoutReporterInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  publicId?: Prisma.StringFieldUpdateOperationsInput | string
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumModerationReportStatusFieldUpdateOperationsInput | $Enums.ModerationReportStatus
  placeId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ModerationReportUncheckedUpdateManyWithoutReporterInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  publicId?: Prisma.StringFieldUpdateOperationsInput | string
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumModerationReportStatusFieldUpdateOperationsInput | $Enums.ModerationReportStatus
  placeId?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type ModerationReportSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  publicId?: boolean
  reason?: boolean
  status?: boolean
  reporterId?: boolean
  placeId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  reporter?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  place?: boolean | Prisma.ModerationReport$placeArgs<ExtArgs>
}, ExtArgs["result"]["moderationReport"]>

export type ModerationReportSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  publicId?: boolean
  reason?: boolean
  status?: boolean
  reporterId?: boolean
  placeId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  reporter?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  place?: boolean | Prisma.ModerationReport$placeArgs<ExtArgs>
}, ExtArgs["result"]["moderationReport"]>

export type ModerationReportSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  publicId?: boolean
  reason?: boolean
  status?: boolean
  reporterId?: boolean
  placeId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  reporter?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  place?: boolean | Prisma.ModerationReport$placeArgs<ExtArgs>
}, ExtArgs["result"]["moderationReport"]>

export type ModerationReportSelectScalar = {
  id?: boolean
  publicId?: boolean
  reason?: boolean
  status?: boolean
  reporterId?: boolean
  placeId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ModerationReportOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "publicId" | "reason" | "status" | "reporterId" | "placeId" | "createdAt" | "updatedAt", ExtArgs["result"]["moderationReport"]>
export type ModerationReportInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  reporter?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  place?: boolean | Prisma.ModerationReport$placeArgs<ExtArgs>
}
export type ModerationReportIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  reporter?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  place?: boolean | Prisma.ModerationReport$placeArgs<ExtArgs>
}
export type ModerationReportIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  reporter?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  place?: boolean | Prisma.ModerationReport$placeArgs<ExtArgs>
}

export type $ModerationReportPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ModerationReport"
  objects: {
    reporter: Prisma.$UserPayload<ExtArgs>
    place: Prisma.$PlacePayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    publicId: string
    reason: string
    status: $Enums.ModerationReportStatus
    reporterId: number
    placeId: number | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["moderationReport"]>
  composites: {}
}

export type ModerationReportGetPayload<S extends boolean | null | undefined | ModerationReportDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ModerationReportPayload, S>

export type ModerationReportCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ModerationReportFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ModerationReportCountAggregateInputType | true
  }

export interface ModerationReportDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ModerationReport'], meta: { name: 'ModerationReport' } }
  /**
   * Find zero or one ModerationReport that matches the filter.
   * @param {ModerationReportFindUniqueArgs} args - Arguments to find a ModerationReport
   * @example
   * // Get one ModerationReport
   * const moderationReport = await prisma.moderationReport.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ModerationReportFindUniqueArgs>(args: Prisma.SelectSubset<T, ModerationReportFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ModerationReportClient<runtime.Types.Result.GetResult<Prisma.$ModerationReportPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ModerationReport that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ModerationReportFindUniqueOrThrowArgs} args - Arguments to find a ModerationReport
   * @example
   * // Get one ModerationReport
   * const moderationReport = await prisma.moderationReport.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ModerationReportFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ModerationReportFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ModerationReportClient<runtime.Types.Result.GetResult<Prisma.$ModerationReportPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ModerationReport that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ModerationReportFindFirstArgs} args - Arguments to find a ModerationReport
   * @example
   * // Get one ModerationReport
   * const moderationReport = await prisma.moderationReport.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ModerationReportFindFirstArgs>(args?: Prisma.SelectSubset<T, ModerationReportFindFirstArgs<ExtArgs>>): Prisma.Prisma__ModerationReportClient<runtime.Types.Result.GetResult<Prisma.$ModerationReportPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ModerationReport that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ModerationReportFindFirstOrThrowArgs} args - Arguments to find a ModerationReport
   * @example
   * // Get one ModerationReport
   * const moderationReport = await prisma.moderationReport.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ModerationReportFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ModerationReportFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ModerationReportClient<runtime.Types.Result.GetResult<Prisma.$ModerationReportPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ModerationReports that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ModerationReportFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ModerationReports
   * const moderationReports = await prisma.moderationReport.findMany()
   * 
   * // Get first 10 ModerationReports
   * const moderationReports = await prisma.moderationReport.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const moderationReportWithIdOnly = await prisma.moderationReport.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ModerationReportFindManyArgs>(args?: Prisma.SelectSubset<T, ModerationReportFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ModerationReportPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ModerationReport.
   * @param {ModerationReportCreateArgs} args - Arguments to create a ModerationReport.
   * @example
   * // Create one ModerationReport
   * const ModerationReport = await prisma.moderationReport.create({
   *   data: {
   *     // ... data to create a ModerationReport
   *   }
   * })
   * 
   */
  create<T extends ModerationReportCreateArgs>(args: Prisma.SelectSubset<T, ModerationReportCreateArgs<ExtArgs>>): Prisma.Prisma__ModerationReportClient<runtime.Types.Result.GetResult<Prisma.$ModerationReportPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ModerationReports.
   * @param {ModerationReportCreateManyArgs} args - Arguments to create many ModerationReports.
   * @example
   * // Create many ModerationReports
   * const moderationReport = await prisma.moderationReport.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ModerationReportCreateManyArgs>(args?: Prisma.SelectSubset<T, ModerationReportCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ModerationReports and returns the data saved in the database.
   * @param {ModerationReportCreateManyAndReturnArgs} args - Arguments to create many ModerationReports.
   * @example
   * // Create many ModerationReports
   * const moderationReport = await prisma.moderationReport.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ModerationReports and only return the `id`
   * const moderationReportWithIdOnly = await prisma.moderationReport.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ModerationReportCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ModerationReportCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ModerationReportPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ModerationReport.
   * @param {ModerationReportDeleteArgs} args - Arguments to delete one ModerationReport.
   * @example
   * // Delete one ModerationReport
   * const ModerationReport = await prisma.moderationReport.delete({
   *   where: {
   *     // ... filter to delete one ModerationReport
   *   }
   * })
   * 
   */
  delete<T extends ModerationReportDeleteArgs>(args: Prisma.SelectSubset<T, ModerationReportDeleteArgs<ExtArgs>>): Prisma.Prisma__ModerationReportClient<runtime.Types.Result.GetResult<Prisma.$ModerationReportPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ModerationReport.
   * @param {ModerationReportUpdateArgs} args - Arguments to update one ModerationReport.
   * @example
   * // Update one ModerationReport
   * const moderationReport = await prisma.moderationReport.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ModerationReportUpdateArgs>(args: Prisma.SelectSubset<T, ModerationReportUpdateArgs<ExtArgs>>): Prisma.Prisma__ModerationReportClient<runtime.Types.Result.GetResult<Prisma.$ModerationReportPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ModerationReports.
   * @param {ModerationReportDeleteManyArgs} args - Arguments to filter ModerationReports to delete.
   * @example
   * // Delete a few ModerationReports
   * const { count } = await prisma.moderationReport.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ModerationReportDeleteManyArgs>(args?: Prisma.SelectSubset<T, ModerationReportDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ModerationReports.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ModerationReportUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ModerationReports
   * const moderationReport = await prisma.moderationReport.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ModerationReportUpdateManyArgs>(args: Prisma.SelectSubset<T, ModerationReportUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ModerationReports and returns the data updated in the database.
   * @param {ModerationReportUpdateManyAndReturnArgs} args - Arguments to update many ModerationReports.
   * @example
   * // Update many ModerationReports
   * const moderationReport = await prisma.moderationReport.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ModerationReports and only return the `id`
   * const moderationReportWithIdOnly = await prisma.moderationReport.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ModerationReportUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ModerationReportUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ModerationReportPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ModerationReport.
   * @param {ModerationReportUpsertArgs} args - Arguments to update or create a ModerationReport.
   * @example
   * // Update or create a ModerationReport
   * const moderationReport = await prisma.moderationReport.upsert({
   *   create: {
   *     // ... data to create a ModerationReport
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ModerationReport we want to update
   *   }
   * })
   */
  upsert<T extends ModerationReportUpsertArgs>(args: Prisma.SelectSubset<T, ModerationReportUpsertArgs<ExtArgs>>): Prisma.Prisma__ModerationReportClient<runtime.Types.Result.GetResult<Prisma.$ModerationReportPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ModerationReports.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ModerationReportCountArgs} args - Arguments to filter ModerationReports to count.
   * @example
   * // Count the number of ModerationReports
   * const count = await prisma.moderationReport.count({
   *   where: {
   *     // ... the filter for the ModerationReports we want to count
   *   }
   * })
  **/
  count<T extends ModerationReportCountArgs>(
    args?: Prisma.Subset<T, ModerationReportCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ModerationReportCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ModerationReport.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ModerationReportAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ModerationReportAggregateArgs>(args: Prisma.Subset<T, ModerationReportAggregateArgs>): Prisma.PrismaPromise<GetModerationReportAggregateType<T>>

  /**
   * Group by ModerationReport.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ModerationReportGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ModerationReportGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ModerationReportGroupByArgs['orderBy'] }
      : { orderBy?: ModerationReportGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ModerationReportGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetModerationReportGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ModerationReport model
 */
readonly fields: ModerationReportFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ModerationReport.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ModerationReportClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  reporter<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  place<T extends Prisma.ModerationReport$placeArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ModerationReport$placeArgs<ExtArgs>>): Prisma.Prisma__PlaceClient<runtime.Types.Result.GetResult<Prisma.$PlacePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ModerationReport model
 */
export interface ModerationReportFieldRefs {
  readonly id: Prisma.FieldRef<"ModerationReport", 'Int'>
  readonly publicId: Prisma.FieldRef<"ModerationReport", 'String'>
  readonly reason: Prisma.FieldRef<"ModerationReport", 'String'>
  readonly status: Prisma.FieldRef<"ModerationReport", 'ModerationReportStatus'>
  readonly reporterId: Prisma.FieldRef<"ModerationReport", 'Int'>
  readonly placeId: Prisma.FieldRef<"ModerationReport", 'Int'>
  readonly createdAt: Prisma.FieldRef<"ModerationReport", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"ModerationReport", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ModerationReport findUnique
 */
export type ModerationReportFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModerationReport
   */
  select?: Prisma.ModerationReportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModerationReport
   */
  omit?: Prisma.ModerationReportOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModerationReportInclude<ExtArgs> | null
  /**
   * Filter, which ModerationReport to fetch.
   */
  where: Prisma.ModerationReportWhereUniqueInput
}

/**
 * ModerationReport findUniqueOrThrow
 */
export type ModerationReportFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModerationReport
   */
  select?: Prisma.ModerationReportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModerationReport
   */
  omit?: Prisma.ModerationReportOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModerationReportInclude<ExtArgs> | null
  /**
   * Filter, which ModerationReport to fetch.
   */
  where: Prisma.ModerationReportWhereUniqueInput
}

/**
 * ModerationReport findFirst
 */
export type ModerationReportFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModerationReport
   */
  select?: Prisma.ModerationReportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModerationReport
   */
  omit?: Prisma.ModerationReportOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModerationReportInclude<ExtArgs> | null
  /**
   * Filter, which ModerationReport to fetch.
   */
  where?: Prisma.ModerationReportWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ModerationReports to fetch.
   */
  orderBy?: Prisma.ModerationReportOrderByWithRelationInput | Prisma.ModerationReportOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ModerationReports.
   */
  cursor?: Prisma.ModerationReportWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ModerationReports from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ModerationReports.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ModerationReports.
   */
  distinct?: Prisma.ModerationReportScalarFieldEnum | Prisma.ModerationReportScalarFieldEnum[]
}

/**
 * ModerationReport findFirstOrThrow
 */
export type ModerationReportFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModerationReport
   */
  select?: Prisma.ModerationReportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModerationReport
   */
  omit?: Prisma.ModerationReportOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModerationReportInclude<ExtArgs> | null
  /**
   * Filter, which ModerationReport to fetch.
   */
  where?: Prisma.ModerationReportWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ModerationReports to fetch.
   */
  orderBy?: Prisma.ModerationReportOrderByWithRelationInput | Prisma.ModerationReportOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ModerationReports.
   */
  cursor?: Prisma.ModerationReportWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ModerationReports from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ModerationReports.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ModerationReports.
   */
  distinct?: Prisma.ModerationReportScalarFieldEnum | Prisma.ModerationReportScalarFieldEnum[]
}

/**
 * ModerationReport findMany
 */
export type ModerationReportFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModerationReport
   */
  select?: Prisma.ModerationReportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModerationReport
   */
  omit?: Prisma.ModerationReportOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModerationReportInclude<ExtArgs> | null
  /**
   * Filter, which ModerationReports to fetch.
   */
  where?: Prisma.ModerationReportWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ModerationReports to fetch.
   */
  orderBy?: Prisma.ModerationReportOrderByWithRelationInput | Prisma.ModerationReportOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ModerationReports.
   */
  cursor?: Prisma.ModerationReportWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ModerationReports from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ModerationReports.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ModerationReports.
   */
  distinct?: Prisma.ModerationReportScalarFieldEnum | Prisma.ModerationReportScalarFieldEnum[]
}

/**
 * ModerationReport create
 */
export type ModerationReportCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModerationReport
   */
  select?: Prisma.ModerationReportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModerationReport
   */
  omit?: Prisma.ModerationReportOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModerationReportInclude<ExtArgs> | null
  /**
   * The data needed to create a ModerationReport.
   */
  data: Prisma.XOR<Prisma.ModerationReportCreateInput, Prisma.ModerationReportUncheckedCreateInput>
}

/**
 * ModerationReport createMany
 */
export type ModerationReportCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ModerationReports.
   */
  data: Prisma.ModerationReportCreateManyInput | Prisma.ModerationReportCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ModerationReport createManyAndReturn
 */
export type ModerationReportCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModerationReport
   */
  select?: Prisma.ModerationReportSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ModerationReport
   */
  omit?: Prisma.ModerationReportOmit<ExtArgs> | null
  /**
   * The data used to create many ModerationReports.
   */
  data: Prisma.ModerationReportCreateManyInput | Prisma.ModerationReportCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModerationReportIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ModerationReport update
 */
export type ModerationReportUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModerationReport
   */
  select?: Prisma.ModerationReportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModerationReport
   */
  omit?: Prisma.ModerationReportOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModerationReportInclude<ExtArgs> | null
  /**
   * The data needed to update a ModerationReport.
   */
  data: Prisma.XOR<Prisma.ModerationReportUpdateInput, Prisma.ModerationReportUncheckedUpdateInput>
  /**
   * Choose, which ModerationReport to update.
   */
  where: Prisma.ModerationReportWhereUniqueInput
}

/**
 * ModerationReport updateMany
 */
export type ModerationReportUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ModerationReports.
   */
  data: Prisma.XOR<Prisma.ModerationReportUpdateManyMutationInput, Prisma.ModerationReportUncheckedUpdateManyInput>
  /**
   * Filter which ModerationReports to update
   */
  where?: Prisma.ModerationReportWhereInput
  /**
   * Limit how many ModerationReports to update.
   */
  limit?: number
}

/**
 * ModerationReport updateManyAndReturn
 */
export type ModerationReportUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModerationReport
   */
  select?: Prisma.ModerationReportSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ModerationReport
   */
  omit?: Prisma.ModerationReportOmit<ExtArgs> | null
  /**
   * The data used to update ModerationReports.
   */
  data: Prisma.XOR<Prisma.ModerationReportUpdateManyMutationInput, Prisma.ModerationReportUncheckedUpdateManyInput>
  /**
   * Filter which ModerationReports to update
   */
  where?: Prisma.ModerationReportWhereInput
  /**
   * Limit how many ModerationReports to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModerationReportIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ModerationReport upsert
 */
export type ModerationReportUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModerationReport
   */
  select?: Prisma.ModerationReportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModerationReport
   */
  omit?: Prisma.ModerationReportOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModerationReportInclude<ExtArgs> | null
  /**
   * The filter to search for the ModerationReport to update in case it exists.
   */
  where: Prisma.ModerationReportWhereUniqueInput
  /**
   * In case the ModerationReport found by the `where` argument doesn't exist, create a new ModerationReport with this data.
   */
  create: Prisma.XOR<Prisma.ModerationReportCreateInput, Prisma.ModerationReportUncheckedCreateInput>
  /**
   * In case the ModerationReport was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ModerationReportUpdateInput, Prisma.ModerationReportUncheckedUpdateInput>
}

/**
 * ModerationReport delete
 */
export type ModerationReportDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModerationReport
   */
  select?: Prisma.ModerationReportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModerationReport
   */
  omit?: Prisma.ModerationReportOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModerationReportInclude<ExtArgs> | null
  /**
   * Filter which ModerationReport to delete.
   */
  where: Prisma.ModerationReportWhereUniqueInput
}

/**
 * ModerationReport deleteMany
 */
export type ModerationReportDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ModerationReports to delete
   */
  where?: Prisma.ModerationReportWhereInput
  /**
   * Limit how many ModerationReports to delete.
   */
  limit?: number
}

/**
 * ModerationReport.place
 */
export type ModerationReport$placeArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Place
   */
  select?: Prisma.PlaceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Place
   */
  omit?: Prisma.PlaceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PlaceInclude<ExtArgs> | null
  where?: Prisma.PlaceWhereInput
}

/**
 * ModerationReport without action
 */
export type ModerationReportDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ModerationReport
   */
  select?: Prisma.ModerationReportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ModerationReport
   */
  omit?: Prisma.ModerationReportOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ModerationReportInclude<ExtArgs> | null
}
