
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.js'
export type * from './prismaNamespace.js'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  AuthenticationAudit: 'AuthenticationAudit',
  Notification: 'Notification',
  Place: 'Place',
  PlaceVote: 'PlaceVote',
  Group: 'Group',
  GroupMember: 'GroupMember',
  Friendship: 'Friendship',
  ModerationReport: 'ModerationReport',
  User: 'User'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const AuthenticationAuditScalarFieldEnum = {
  id: 'id',
  ipAddress: 'ipAddress',
  remotePort: 'remotePort',
  userAgent: 'userAgent',
  origin: 'origin',
  status: 'status',
  userId: 'userId',
  createdAt: 'createdAt'
} as const

export type AuthenticationAuditScalarFieldEnum = (typeof AuthenticationAuditScalarFieldEnum)[keyof typeof AuthenticationAuditScalarFieldEnum]


export const NotificationScalarFieldEnum = {
  id: 'id',
  publicId: 'publicId',
  userId: 'userId',
  actorId: 'actorId',
  type: 'type',
  groupKey: 'groupKey',
  title: 'title',
  body: 'body',
  data: 'data',
  readAt: 'readAt',
  createdAt: 'createdAt'
} as const

export type NotificationScalarFieldEnum = (typeof NotificationScalarFieldEnum)[keyof typeof NotificationScalarFieldEnum]


export const PlaceScalarFieldEnum = {
  id: 'id',
  publicId: 'publicId',
  googlePlaceId: 'googlePlaceId',
  name: 'name',
  googlePlaceName: 'googlePlaceName',
  nickname: 'nickname',
  formattedAddress: 'formattedAddress',
  latitude: 'latitude',
  longitude: 'longitude',
  city: 'city',
  state: 'state',
  country: 'country',
  photoUrl: 'photoUrl',
  websiteUrl: 'websiteUrl',
  mapsUrl: 'mapsUrl',
  isActive: 'isActive',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type PlaceScalarFieldEnum = (typeof PlaceScalarFieldEnum)[keyof typeof PlaceScalarFieldEnum]


export const PlaceVoteScalarFieldEnum = {
  id: 'id',
  publicId: 'publicId',
  day: 'day',
  note: 'note',
  status: 'status',
  voteType: 'voteType',
  showIdentity: 'showIdentity',
  going: 'going',
  voteTime: 'voteTime',
  scopeKey: 'scopeKey',
  userId: 'userId',
  placeId: 'placeId',
  groupId: 'groupId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type PlaceVoteScalarFieldEnum = (typeof PlaceVoteScalarFieldEnum)[keyof typeof PlaceVoteScalarFieldEnum]


export const GroupScalarFieldEnum = {
  id: 'id',
  publicId: 'publicId',
  name: 'name',
  slug: 'slug',
  description: 'description',
  privacy: 'privacy',
  passwordHash: 'passwordHash',
  city: 'city',
  state: 'state',
  createdById: 'createdById',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type GroupScalarFieldEnum = (typeof GroupScalarFieldEnum)[keyof typeof GroupScalarFieldEnum]


export const GroupMemberScalarFieldEnum = {
  id: 'id',
  groupId: 'groupId',
  userId: 'userId',
  role: 'role',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type GroupMemberScalarFieldEnum = (typeof GroupMemberScalarFieldEnum)[keyof typeof GroupMemberScalarFieldEnum]


export const FriendshipScalarFieldEnum = {
  id: 'id',
  requesterId: 'requesterId',
  addresseeId: 'addresseeId',
  pairKey: 'pairKey',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type FriendshipScalarFieldEnum = (typeof FriendshipScalarFieldEnum)[keyof typeof FriendshipScalarFieldEnum]


export const ModerationReportScalarFieldEnum = {
  id: 'id',
  publicId: 'publicId',
  reason: 'reason',
  status: 'status',
  reporterId: 'reporterId',
  placeId: 'placeId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ModerationReportScalarFieldEnum = (typeof ModerationReportScalarFieldEnum)[keyof typeof ModerationReportScalarFieldEnum]


export const UserScalarFieldEnum = {
  id: 'id',
  publicId: 'publicId',
  name: 'name',
  username: 'username',
  email: 'email',
  passwordHash: 'passwordHash',
  googleId: 'googleId',
  avatarEncryptedPath: 'avatarEncryptedPath',
  avatarIv: 'avatarIv',
  avatarAuthTag: 'avatarAuthTag',
  avatarMimeType: 'avatarMimeType',
  avatarOriginalName: 'avatarOriginalName',
  avatarUpdatedAt: 'avatarUpdatedAt',
  loginAttempts: 'loginAttempts',
  lastLogin: 'lastLogin',
  role: 'role',
  token: 'token',
  tokenExpiresAt: 'tokenExpiresAt',
  emailVerifiedAt: 'emailVerifiedAt',
  emailVerificationTokenHash: 'emailVerificationTokenHash',
  emailVerificationTokenExpiresAt: 'emailVerificationTokenExpiresAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  passwordChangedAt: 'passwordChangedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullableJsonNullValueInput = {
  DbNull: DbNull,
  JsonNull: JsonNull
} as const

export type NullableJsonNullValueInput = (typeof NullableJsonNullValueInput)[keyof typeof NullableJsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]

