
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const AuthenticationStatus = {
  SUCCESS: 'SUCCESS',
  USER_NOT_EXISTS: 'USER_NOT_EXISTS',
  INCORRECT_PASSWORD: 'INCORRECT_PASSWORD',
  RECOVER_PASSWORD: 'RECOVER_PASSWORD',
  INVALID_TOKEN: 'INVALID_TOKEN',
  BLOCKED: 'BLOCKED'
} as const

export type AuthenticationStatus = (typeof AuthenticationStatus)[keyof typeof AuthenticationStatus]


export const UserRole = {
  ADMIN: 'ADMIN',
  DEFAULT: 'DEFAULT'
} as const

export type UserRole = (typeof UserRole)[keyof typeof UserRole]
