
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const AuthenticationStatus = {
  SUCCESS: 'SUCCESS',
  USER_NOT_EXISTS: 'USER_NOT_EXISTS',
  INCORRECT_PASSWORD: 'INCORRECT_PASSWORD',
  RECOVER_PASSWORD: 'RECOVER_PASSWORD',
  INVALID_TOKEN: 'INVALID_TOKEN',
  BLOCKED: 'BLOCKED'
} as const

export type AuthenticationStatus = (typeof AuthenticationStatus)[keyof typeof AuthenticationStatus]


export const GroupPrivacy = {
  PUBLIC: 'PUBLIC',
  PRIVATE: 'PRIVATE'
} as const

export type GroupPrivacy = (typeof GroupPrivacy)[keyof typeof GroupPrivacy]


export const GroupMemberRole = {
  OWNER: 'OWNER',
  MODERATOR: 'MODERATOR',
  MEMBER: 'MEMBER'
} as const

export type GroupMemberRole = (typeof GroupMemberRole)[keyof typeof GroupMemberRole]


export const GroupMemberStatus = {
  ACTIVE: 'ACTIVE',
  PENDING: 'PENDING',
  BLOCKED: 'BLOCKED'
} as const

export type GroupMemberStatus = (typeof GroupMemberStatus)[keyof typeof GroupMemberStatus]


export const VoteStatus = {
  ACTIVE: 'ACTIVE',
  CANCELLED: 'CANCELLED'
} as const

export type VoteStatus = (typeof VoteStatus)[keyof typeof VoteStatus]


export const VoteType = {
  GENERAL: 'GENERAL',
  MUSIC: 'MUSIC',
  FOOD: 'FOOD',
  DRINK: 'DRINK'
} as const

export type VoteType = (typeof VoteType)[keyof typeof VoteType]


export const FriendshipStatus = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  BLOCKED: 'BLOCKED'
} as const

export type FriendshipStatus = (typeof FriendshipStatus)[keyof typeof FriendshipStatus]


export const ModerationReportStatus = {
  OPEN: 'OPEN',
  RESOLVED: 'RESOLVED',
  DISMISSED: 'DISMISSED'
} as const

export type ModerationReportStatus = (typeof ModerationReportStatus)[keyof typeof ModerationReportStatus]


export const UserRole = {
  ADMIN: 'ADMIN',
  DEFAULT: 'DEFAULT'
} as const

export type UserRole = (typeof UserRole)[keyof typeof UserRole]
